---
driver:
  name: docker
  privileged: true
  binary: docker.io
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  attributes:
    test-kitchen: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[sample_test]